"""empty message

Revision ID: 3689fb3d57bd
Revises: 512d2bf44c16
Create Date: 2023-05-07 17:08:30.745392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3689fb3d57bd'
down_revision = '512d2bf44c16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('migrateTestAdd')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('migrateTestAdd', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
