"""empty message

Revision ID: 717a45e39a54
Revises: 3689fb3d57bd
Create Date: 2023-05-11 16:17:03.875575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '717a45e39a54'
down_revision = '3689fb3d57bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_mode', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.drop_column('game_mode')

    # ### end Alembic commands ###
